#ifndef __SPI_FLASH_H__
#define __SPI_FLASH_H__

//#define __H6__ 1 //2K1000平台编译需要注释该行
#define __LX2K1000__ 1 //H6平台编译需要注释该行

#define SPI_FLASH_UID_OFFSET 0
#define SPI_FLASH_UID_LEN 32

#define SPI_FLASH_MODEL_NAME_OFFSET SPI_FLASH_UID_OFFSET + SPI_FLASH_UID_LEN
#define SPI_FLASH_MODEL_NAME_LEN 64

#define SPI_FLASH_USB_NAME_OFFSET SPI_FLASH_MODEL_NAME_OFFSET + SPI_FLASH_MODEL_NAME_LEN
#define SPI_FLASH_USB_NAME_LEN 64

#define SPI_FLASH_MAC_OFFSET SPI_FLASH_USB_NAME_OFFSET + SPI_FLASH_USB_NAME_LEN
#define SPI_FLASH_MAC_LEN 6

#define SPI_FLASH_IP_OFFSET SPI_FLASH_MAC_OFFSET + SPI_FLASH_MAC_LEN
#define SPI_FLASH_NET_LEN 4

#define SPI_FLASH_NETMASK_OFFSET SPI_FLASH_IP_OFFSET + SPI_FLASH_NET_LEN

#define SPI_FLASH_GATEWAY_OFFSET SPI_FLASH_NETMASK_OFFSET + SPI_FLASH_NET_LEN

#endif
